name: Deploy Github page
on:
  push:
    branches:
      - develop
      - feature/google-oauth
env:
  CI: ''
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }} 🚀
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Make .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_API_URI: ${{secrets.REACT_APP_API_URI}}
          envkey_REACT_APP_CLIENT_ID: ${{secrets.REACT_APP_CLIENT_ID}}
          envkey_REACT_APP_REDIRECT_URI: ${{secrets.REACT_APP_REDIRECT_URI}}
          file_name: .env

      - name: Cache node_modules 🚀
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.OS }}-build-${{ runner.OS }}-

      - name: Install and build 🚀
        run: |
          yarn install
          yarn run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: deploy
          FOLDER: build
          CLEAN: true
